global:
  smtp_smarthost: "smtp.sendgrid.net:587"
  smtp_from: "lourdes.arulsebas@gmail.com"
  smtp_auth_username: "apikey"
  smtp_auth_password: "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"
  smtp_require_tls: true  # Ensure encrypted email transmission

route:
  group_by: ['alertname']   # Grouping alerts by name
  group_wait: 10s           # Wait before sending first alert
  group_interval: 5m        # Time between sending repeated alerts
  repeat_interval: 3h       # Prevents alert spamming
  receiver: "critical_email"
  matchers:
    - severity="critical"   # 🔹 This ensures only "critical" alerts are sent

receivers:
  - name: "critical_email"
    email_configs:
      - to: "arulsebas@gmail.com"
        require_tls: true
