global:
  smtp_smarthost: "smtp.sendgrid.net:587"
  smtp_from: "lourdes.arulsebas@gmail.com"
  smtp_auth_username: "${api}"
  smtp_auth_password: "${SMTP_PASSWORD}"
  smtp_require_tls: true  # Ensure encrypted email transmission

route:
  receiver: "critical_email"

receivers:
  - name: "critical_email"
    email_configs:
      - to: "arulsebas@gmail.com"
        require_tls: true
