version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets:/etc/prometheus/targets
      - /etc/hosts:/etc/hosts
    cap_add:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - seccomp=unconfined
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-admin-api"
    networks:
      - monitoring
    restart: unless-stopped

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    volumes:
      - victoriametrics-data:/victoria-metrics-data
    ports:
      - "8428:8428"
    command:
      - "--storageDataPath=/victoria-metrics-data"
      - "--retentionPeriod=180"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest  
    container_name: blackbox-exporter
    ports:
      - "9115:9115"   
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
      -  /etc/hosts:/etc/hosts
    cap_add:
      - NET_RAW
      - NET_ADMIN   
    security_opt:
      - seccomp=unconfined 
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"
      - "--log.level=debug"  
    networks:
      - monitoring
    restart: unless-stopped

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    ports:
      - "9116:9116"
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
      - /etc/hosts:/etc/hosts
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
      - "--log.level=debug"
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  victoriametrics-data:
  grafana-data:

